application: jaggeree-staging
version: 1
runtime: python
api_version: 1

handlers:
- url: /xd_receiver.htm
  static_files: static/xd_receiver.htm
  upload: static/xd_receiver.htm

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
    
- url: /styles
  static_dir: static/styles

- url: /images
  static_dir: static/images
  
- url: /js
  static_dir: static/js

- url: .*
  script: main.py
